apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "zammad.fullname" . }}
  labels:
    app: {{ template "zammad.name" . }}
    chart: {{ template "zammad.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "zammad.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "zammad.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: {{ .Chart.Name }}-init
        image: {{ .Values.zammad.image.repository }}:zammad-{{ .Values.zammad.image.tag }}
        args: [ "zammad-init" ]
        env:
        {{- range $key, $value := .Values.zammad.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        imagePullPolicy: {{ .Values.zammad.image.pullPolicy }}
        volumeMounts:
         - name: {{ template "zammad.fullname" . }}
           mountPath: /opt/zammad
      containers:
      - name: {{ .Chart.Name }}-nginx
        image: {{ .Values.zammad.image.repository }}:zammad-{{ .Values.zammad.image.tag }}
        args: [ "zammad-nginx" ]
        env:
        {{- range $key, $value := .Values.zammad.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        ports:
        - containerPort: 80
          name: nginx
        imagePullPolicy: {{ .Values.zammad.image.pullPolicy }}
        volumeMounts:
         - name: {{ template "zammad.fullname" . }}
           mountPath: /opt/zammad
         - name: {{ template "zammad.fullname" . }}-nginx
           mountPath: /etc/nginx/sites-enabled
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          resources:
{{ toYaml .Values.zammad.resources.nginx | indent 12 }}
      - name: {{ .Chart.Name }}-railsserver
        image: {{ .Values.zammad.image.repository }}:zammad-{{ .Values.zammad.image.tag }}
        args: ["zammad-railsserver"]
        env:
        {{- range $key, $value := .Values.zammad.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        imagePullPolicy: {{ .Values.zammad.image.pullPolicy }}
        ports:
        - name: railsserver
          containerPort: 3000
        volumeMounts:
         - name: {{ template "zammad.fullname" . }}
           mountPath: /opt/zammad
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 10
          resources:
{{ toYaml .Values.zammad.resources.railsserver | indent 12 }}
      - name: {{ .Chart.Name }}-scheduler
        image: {{ .Values.zammad.image.repository }}:zammad-{{ .Values.zammad.image.tag }}
        args: [ "zammad-scheduler" ]
        env:
        {{- range $key, $value := .Values.zammad.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        imagePullPolicy: {{ .Values.zammad.image.pullPolicy }}
        volumeMounts:
         - name: {{ template "zammad.fullname" . }}
           mountPath: /opt/zammad
           resources:
{{ toYaml .Values.zammad.resources.scheduler | indent 12 }}
      - name: {{ .Chart.Name }}-websocket
        image: {{ .Values.zammad.image.repository }}:zammad-{{ .Values.zammad.image.tag }}
        args: [ "zammad-websocket" ]
        env:
        {{- range $key, $value := .Values.zammad.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        imagePullPolicy: Always
        ports:
        - name: websocket
          containerPort: 6042
        volumeMounts:
         - name: zammad
           mountPath: /opt/zammad
        readinessProbe:
          tcpSocket:
            port: 6042
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6042
          initialDelaySeconds: 60
          periodSeconds: 10
          resources:
{{ toYaml .Values.zammad.resources.websocket | indent 12 }}
    {{- with .Values.zammad.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.zammad.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.zammad.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: {{ template "zammad.fullname" . }}-nginx
        configMap:
          name: {{ template "zammad.fullname" . }}-nginx
      - name: {{ template "zammad.fullname" . }}
      {{- if .Values.zammad.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.zammad.persistence.existingClaim | default (include "zammad.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
