apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "zammad.fullname" . }}
  labels:
    app: {{ template "zammad.name" . }}
    chart: {{ template "zammad.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "zammad.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "zammad.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: {{ .Chart.Name }}-init
        image: {{ .Values.image.repository }}:zammad-{{ .Values.image.tag }}
        args: [ "zammad-init" ]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
         - name: {{ template "zammad.fullname" . }}
           mountPath: /opt/zammad
      containers:
      - name: {{ .Chart.Name }}-nginx
        image: {{ .Values.image.repository }}:zammad-{{ .Values.image.tag }}
        args: [ "zammad-nginx" ]
        ports:
        - containerPort: 80
          name: nginx
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
         - name: {{ template "zammad.fullname" . }}
           mountPath: /opt/zammad
         - name: {{ template "zammad.fullname" . }}-config-nginx
           mountPath: /etc/nginx/sites-enabled
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          resources:
{{ toYaml .Values.resources.nginx | indent 12 }}
      - name: {{ .Chart.Name }}-railsserver
        image: {{ .Values.image.repository }}:zammad-{{ .Values.image.tag }}
        args: ["zammad-railsserver"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: railsserver
          containerPort: 3000
        volumeMounts:
         - name: {{ template "zammad.fullname" . }}
           mountPath: /opt/zammad
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 10
          resources:
{{ toYaml .Values.resources.railsserver | indent 12 }}
      - name: {{ .Chart.Name }}-scheduler
        image: {{ .Values.image.repository }}:zammad-{{ .Values.image.tag }}
        args: [ "zammad-scheduler" ]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
         - name: {{ template "zammad.fullname" . }}
           mountPath: /opt/zammad
           resources:
{{ toYaml .Values.resources.scheduler | indent 12 }}
      - name: {{ .Chart.Name }}-websocket
        image: {{ .Values.image.repository }}:zammad-{{ .Values.image.tag }}
        args: [ "zammad-websocket" ]
        imagePullPolicy: Always
        ports:
        - name: websocket
          containerPort: 6042
        volumeMounts:
         - name: zammad
           mountPath: /opt/zammad
        readinessProbe:
          tcpSocket:
            port: 6042
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6042
          initialDelaySeconds: 60
          periodSeconds: 10
          resources:
{{ toYaml .Values.resources.websocket | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
