dependencies:
  - name: elasticsearch
    repository: ttps://kubernetes-charts.storage.googleapis.com/
    version: 1.11.1
    condition: useElasticsearch
  - name: memcached
    version: 2.3.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: useMemcached
  - name: postgresql
    version: 1.0.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: usePostgres
