dependencies:
  - name: elasticsearch
    repository: https://kubernetes-charts-incubator.storage.googleapis.com
    version: 1.7.0
    condition: useElasticsearch
  - name: memcached
    version: 2.3.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: useMemcached
  - name: postgresql
    version: 0.18.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: usePostgres
